POST http://localhost:8082/api/auth/login
Content-Type: application/json

{
  "username": "edward",
  "password": 123123
}

###
GET http://localhost:8082/api/private/teacher/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyLGVkd2FyZCx1c2VyIiwiaWF0IjoxNzMwMTEzMTk4LCJleHAiOjE3MzAxMTMzNzh9.iD7rBlAwpP6nq_uPI4sDX5BluJW-Lx3e_vflHsRzktM

###
POST localhost:8081/api/auth/signup
Content-Type: application/json

{
  "username": "edward",
  "email": "edward@test.com",
  "password": "123123",
  "department": "Robotics",
  "name": "Edward Doe"
}

###
POST localhost:8082/api/public/room/search
Content-Type: application/json

{
  "roomType": "CONFERENCE",
  "capacity": 30,
  "hasComputers": false,
  "hasProjectors": false,
  "hasWhiteBoard": false
}

###
DELETE localhost:8082/api/public/booking/booking/10