POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "edward",
  "password": 123123
}

###
GET http://localhost:8081/api/private/teacher/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyLGVkd2FyZCx1c2VyIiwiaWF0IjoxNzMwMDE4Mjg3LCJleHAiOjE3MzAwMTg0Njd9.VcLZB5LcofLy1D6-wc3yzxnvoXQB9R1N8blQHr1sUgk

###
POST localhost:8081/api/auth/signup
Content-Type: application/json

{
  "username": "edward",
  "email": "edward@test.com",
  "password": "123123",
  "department": "Robotics",
  "name": "Edward Doe"
}